<?php

/**
 * Implements hook_element_info().
 */
function zmt_domain_ui_element_info() {
  $types = array();

  $types['zmt_domain_select'] = array(
    '#input' => TRUE,
    '#multiple' => FALSE,
    '#process' => array(
      'zmt_domain_select_expand',
      'form_process_select',
      'ajax_process_form',
    ),
    '#theme' => 'select',
    '#theme_wrappers' => array('form_element'),
    '#server' => NULL,
    '#options' => array(),
  );

  return $types;
}

/**
 * Implements hook_menu().
 */ 
function zmt_domain_ui_menu() {
  $items = array();
  $items['zmt/domain/%zmt_domain'] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('zmt_domain', 2),
    'page callback' => 'zmt_domain_view',
    'page arguments' => array(2),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'zmt_domain', 2),
  );
  $items['zmt/domain/add'] = array(
    'title' => t('Add Domain'),
    'page callback' => 'zmt_domain_add_page',
    'access callback' => 'zmt_domain_add_access',
    'type' => MENU_LOCAL_ACTION,
    'file' => 'zmt_domain.admin.inc',
  );
  $items['zmt/domain/%zmt_domain/edit'] = array(
    'title' => t('Edit Domain'),
    'page callback' => 'zmt_domain_edit_page',
    'page arguments' => array(2),
    'access callback' => 'zmt_domain_edit_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK,
    'file' => 'zmt_domain.admin.inc',
  );
  $items['zmt/domain/%zmt_domain/delete'] = array(
    'title' => t('Delete Domain'),
    'page callback' => 'zmt_domain_delete_page',
    'page arguments' => array(2),
    'access callback' => 'zmt_domain_delete_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK,
    'file' => 'zmt_domain.admin.inc',
  );
  $items['zmt/domain'] = array(
    'title' => t('Domains'),
    'page callback' => 'zmt_domain_list_all',
    'access callback' => 'zmt_domain_list_access',
    'file' => 'zmt_domain.admin.inc',
  );
  return $items;
}

/**
 * Domain view callback.
 */
function zmt_domain_view($domain) {
  backdrop_set_title(entity_label('zmt_domain', $domain));
  return entity_view('zmt_domain', array(entity_id('zmt_domain', $domain) => $domain), 'full');
}

/**
 * Access callback: determines if the user can create domain.
 */
function zmt_domain_list_access($account = NULL) {
  return zmt_domain_access('list', NULL, $account);
}

/**
 * Access callback: determines if the user can create domain.
 */
function zmt_domain_add_access($account = NULL) {
  return zmt_domain_access('create', NULL, $account);
}

/**
 * Access callback: determines if the user can edit domain.
 */
function zmt_domain_edit_access($domain, $account = NULL) {
  return zmt_domain_access('edit', $domain, $account);
}

/**
 * Access callback: determines if the user can delete domain.
 */
function zmt_domain_delete_access($domain, $account = NULL) {
  return zmt_domain_access('delete', $domain, $account);
}

/**
 * Our process callback to expand the domain FAPI element.
 */
function zmt_domain_select_expand($element) {
  if (empty($element['#options'])) {
    $options = array();
    if ($element['#server'] !== NULL) {
      $domains = zmt_domain_load_multiple_by_server($element['#server'], TRUE);
    }
    else {
      if (!(user_access('administer zmt'))) {
        $domains = zmt_domain_load_multiple_by_user();
      }
      else {
        $domains = zmt_domain_load_all();
      }
    }
    foreach ($domains as $domain) {
      $options[$domain->id] = $domain->name;
    }
    $element['#options'] = $options;
    $element['#empty_option'] = t('- None -');
  }
  if (empty($element['#title'])) {
    $element['#title'] = t('Domain');
  }
  if (isset($element['#ajax']) && !isset($element['#ajax']['event'])) {
    $element['#ajax']['event'] = 'change';
  }
  return $element;
}

/**
 * Zimbra filter by domain form.
 */
function zmt_filter_by_domain_form($form, &$form_state) {
  if (user_access('administer zmt')) {
    $server_id = isset($_SESSION['zmt_filter_server_id']) ? (int) $_SESSION['zmt_filter_server_id'] : 0;
    $form['server_id'] = array(
      '#type' => 'zmt_server_select',
      '#default_value' => $server_id,
      '#ajax' => array(
        'callback' => 'zmt_filter_server_select_callback',
        'wrapper' => 'zmt-domain-dropdown-wrap',
        'progress' => array(
          'type' => 'throbber',
          'message' => NULL,
        ),
      ),
      '#suffix' => '&nbsp;',
      '#theme_wrappers' => array(),
    );
  }
  else {
    $server_id = isset($_SESSION['zmt_filter_server_id']) ? (int) $_SESSION['zmt_filter_server_id'] : NULL;
  }

  $domain_id = isset($_SESSION['zmt_filter_domain_id']) ? (int) $_SESSION['zmt_filter_domain_id'] : 0;
  $select_server_id = isset($form_state['values']['server_id']) ? (int) $form_state['values']['server_id'] : $server_id;
  $form['domain_id'] = array(
    '#type' => 'zmt_domain_select',
    '#server' => $select_server_id,
    '#default_value' => $domain_id,
    '#prefix' => '<div id="zmt-domain-dropdown-wrap" style="display:inline-block;">',
    '#suffix' => '</div>',
    '#theme_wrappers' => array(),
  );

  $form['apply'] = array(
    '#type' => 'submit',
    '#value' => t('Filter'),
    '#submit' => array('zmt_filter_by_domain_apply_callback'),
    '#prefix' => '&nbsp;',
  );
  if (!empty($select_server_id) || !empty($domain_id)) {
    $form['reset'] = array(
      '#type' => 'submit',
      '#value' => t('Reset'),
      '#submit' => array('zmt_filter_by_domain_reset_callback'),
    );
  }
  return $form;
}

/**
 * zmt domain filter server select ajax callback.
 */
function zmt_filter_server_select_callback($form, $form_state) {
  return $form['domain_id'];
}

/**
 * zmt domain filter apply callback.
 */
function zmt_filter_by_domain_apply_callback($form, &$form_state) {
  if (isset($form_state['values']['server_id'])) {
    $_SESSION['zmt_filter_server_id'] = (int) $form_state['values']['server_id'];
  }
  $_SESSION['zmt_filter_domain_id'] = (int) $form_state['values']['domain_id'];
  $form_state['redirect'] = current_path();
}

/**
 * zmt domain filter reset callback.
 */
function zmt_filter_by_domain_reset_callback($form, &$form_state){
  unset($_SESSION['zmt_filter_server_id']);
  unset($_SESSION['zmt_filter_domain_id']);
  $form_state['redirect'] = current_path();
}
