<?php

/**
 * Implements hook_entity_info().
 */
function zmt_domain_entity_info() {
  $entity = array(
    'zmt_domain' => array(
      'label' => t('Domain'),
      'entity class' => 'ZmtDomainEntity',
      'controller class' => 'EntityDatabaseStorageController',
      'base table' => 'zmt_domain',
      'fieldable' => FALSE,
      'entity keys' => array(
        'id' => 'id',
        'label' => 'name',
      ),
      'entity cache' => TRUE,
      'bundles' => array(),
      'view modes' => array(
        'full' => array(
          'label' => t('Domain'),
          'custom settings' => FALSE,
        ),
      ),
      'label callback' => 'zmt_domain_label',
      'uri callback' => 'zmt_domain_uri',
      'module' => 'zmt_domain',
      'access callback' => 'zmt_domain_access',
    ),
    'zmt_domain_cos' => array(
      'label' => t('Class of Service for Domain'),
      'entity class' => 'ZmtDomainCosEntity',
      'controller class' => 'EntityDatabaseStorageController',
      'base table' => 'zmt_domain_cos',
      'fieldable' => FALSE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'entity cache' => TRUE,
      'bundles' => array(),
      'module' => 'zmt_domain',
      'access callback' => 'zmt_tenant_access',
    ),
  );

  return $entity;
}

/**
 * Implements hook_entity_property_info_alter().
 */
function zmt_domain_entity_property_info_alter(&$info) {
  $properties = &$info['zmt_domain']['properties'];
  $properties['server'] = array(
    'type' => 'zmt_server',
    'label' => t('Server'),
    'description' => t('The domain\'s server.'),
    'getter callback' => 'zmt_domain_get_properties',
    'schema field' => 'server_id',
  );
  $properties['tenant'] = array(
    'type' => 'zmt_tenant',
    'label' => t('Tenant'),
    'description' => t('The domain\'s tenant.'),
    'getter callback' => 'zmt_domain_get_properties',
    'schema field' => 'tenant_id',
  );
  $properties['user'] = array(
    'type' => 'user',
    'label' => t('User'),
    'description' => t('The user representation of this domain\'s .'),
    'getter callback' => 'zmt_domain_get_properties',
    'schema field' => 'domain_uid',
  );
  $properties['status'] = array(
    'type' => 'text',
    'label' => t('Status'),
    'description' => t('The domain\'s status.'),
    'getter callback' => 'zmt_domain_get_properties',
    'schema field' => 'status',
  );
  $properties['creator'] = array(
    'type' => 'user',
    'label' => t('Creator'),
    'description' => t('The domain\'s creator.'),
    'getter callback' => 'zmt_domain_get_properties',
    'schema field' => 'uid',
  );
}

/**
 * Entity metadata callback to load domain's properties.
 */
function zmt_domain_get_properties($domain, array $options, $name) {
  switch ($name) {
    case 'server':
      return zmt_server_load($domain->server_id);
    case 'tenant':
      return zmt_domain_load($domain->tenant_id);
    case 'user':
      return user_load($domain->tenant_uid);
    case 'status':
      $statuses = zmt_domain_statuses();
      return isset($statuses[$domain->status]) ? $statuses[$domain->status] : '';
    case 'creator':
      return user_load($domain->uid);
  }
}

/**
 * Implements hook_permission().
 */ 
function zmt_domain_permission() {
  return zmt_access_permissions('zmt_domain', 'Domain');
}

/**
 * Implements hook_user_delete().
 */
function zmt_domain_user_delete($domain) {
  db_update('zmt_domain')
    ->fields(array(
      'domain_uid' => 0,
    ))
    ->condition('domain_uid', $domain->uid)
    ->execute();
}

/**
 * Implements hook_zmt_server_delete().
 */ 
function zmt_domain_zmt_server_delete($server){
  $id = $server ? $server->id : 0;
  zmt_domain_delete_multiple_by_server(array($id));
}

/**
 * Implements hook_zmt_cos_delete().
 */ 
function zmt_domain_zmt_cos_delete($cos){
  $id = $cos ? $cos->id : 0;
  zmt_domain_cos_delete_multiple_by_cos(array($id));
}

/**
 * Implements hook_query_TAG_alter() for zmt_domain_load_multiple query tag.
 */ 
function zmt_domain_query_zmt_domain_load_multiple_alter(QueryAlterableInterface $query) {
  $query->leftJoin('zmt_server', 'zs', 'zs.id = base.server_id');
  $query->leftJoin('zmt_tenant', 'zt', 'zt.id = base.tenant_id');
  $query->leftJoin('users', 'tu', 'tu.uid = zt.tenant_uid');
  $query->leftJoin('users', 'du', 'du.uid = base.domain_uid');

  $query->addField('zs', 'name', 'server');
  $query->addField('zs', 'delete_domain');
  $query->addField('tu', 'name', 'tenant');
  $query->addField('du', 'mail', 'mail');
  $query->addField('du', 'status', 'status');
}

/**
 * Implements hook_query_TAG_alter() for zmt_domain_cos_load_multiple query tag.
 */ 
function zmt_domain_query_zmt_domain_cos_load_multiple_alter(QueryAlterableInterface $query) {
  $query->leftJoin('zmt_cos', 'zc', 'zc.id = base.cos_id');
  $query->leftJoin('zmt_domain', 'zd', 'zd.id = base.domain_id');
  $query->addField('zc', 'name', 'cos');
  $query->addField('zd', 'name', 'domain');
}

/**
 * Implements hook_query_TAG_alter() for zmt_tenant_load_multiple query tag.
 */ 
function zmt_domain_query_zmt_server_load_multiple_alter(QueryAlterableInterface $query) {
  $count_domain_query = db_select('zmt_domain', 'zd')
    ->fields('zd', array('server_id'))
    ->groupBy('zd.server_id');
  $count_domain_query->addExpression('COUNT(zd.id)', 'total_domain');
  $query->leftJoin($count_domain_query, 'cdq', 'cdq.server_id = base.id');
  $query->addExpression('IFNULL(cdq.total_domain, 0)', 'total_domain');
}

/**
 * Implements hook_query_TAG_alter() for zmt_tenant_load_multiple query tag.
 */ 
function zmt_domain_query_zmt_tenant_load_multiple_alter(QueryAlterableInterface $query) {
  $count_domain_query = db_select('zmt_domain', 'zd')
    ->fields('zd', array('tenant_id'))
    ->groupBy('zd.tenant_id');
  $count_domain_query->addExpression('COUNT(zd.id)', 'total_domain');
  $query->leftJoin($count_domain_query, 'cdq', 'cdq.tenant_id = base.id');
  $query->addExpression('IFNULL(cdq.total_domain, 0)', 'total_domain');
}

/**
 * Access callback for Domain.
 */
function zmt_domain_access($op, $domain, $account = NULL, $entity_type = NULL) {
  global $user;
  if (NULL === $account) {
    $account = $user;
  }
  if (user_access('administer zmt', $account) || user_access('administer any zmt_domain', $account)) {
    return TRUE;
  }
  if ($op === 'list' || $op === 'create') {
    return user_access('administer own zmt_domain', $account);
  }
  else {
    $is_own = isset($domain->uid) && $domain->uid == $account->uid;
    return user_access('administer own zmt_domain', $account) && $is_own;
  }
}

/**
 * Zmt domain entity uri callback.
 */
function zmt_domain_uri($domain) {
  return array(
    'path' => 'zmt/domain/' . $domain->id,
  );
}

/**
 * Zmt domain entity label callback.
 */
function zmt_domain_label($domain, $entity_type) {
  return t('Domain @name', array('@name' => $domain->name));
}

/**
 * Loads a domain by ID.
 *
 * @param $id
 *   A domain ID.
 * @return
 *   A domain object or FALSE.
 */
function zmt_domain_load($id, $reset = FALSE) {
  if (empty($id)) {
    return FALSE;
  }

  $domains = zmt_domain_load_multiple(array($id), array(), $reset);
  return $domains ? reset($domains) : FALSE;
}

/**
 * Loads multiple domain by ID or based on a set of matching conditions.
 *
 * @see entity_load()
 *
 * @param $ids
 *   An array of domain IDs.
 * @param $conditions
 *   An array of conditions on the {zmt_domain} table in the form
 *     'field' => $value.
 * @param $reset
 *   Whether to reset the internal domain loading cache.
 *
 * @return
 *   An array of domain objects indexed by id.
 */
function zmt_domain_load_multiple(array $ids = array(), array $conditions = array(), $reset = FALSE) {
  if (empty($ids) && empty($conditions)) {
    return array();
  }

  return entity_load('zmt_domain', $ids, $conditions, $reset);
}

/**
 * Loads all domain.
 *
 * @return
 *   An array of domain objects indexed by id.
 *
 * @see zmt_domain_load_multiple()
 */
function zmt_domain_load_all($filter_by_user = FALSE, $limit = 0, $offset = 0) {
  global $user;
  $cache = &backdrop_static(__FUNCTION__, array());
  $cache_key = md5(var_export($filter_by_user, TRUE) . $limit . $limit);
  if (!isset($cache[$cache_key])) {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'zmt_domain');
    if ($filter_by_user === TRUE) {
      if (!(user_access('administer zmt')
        || user_access('administer any zmt_domain'))) {
        $query->condition('d.uid', $user->uid);
      }
    }
    if ((int) $limit > 0) {
      $efq->range($offset, $limit);
    }
    $result = $query->execute();
    $ids = isset($result['zmt_domain']) ? array_keys($result['zmt_domain']) : array();
    $cache[$cache_key] = zmt_domain_load_multiple($ids);
  }
  return $cache[$cache_key];
}

/**
 * Loads multiple domain by server.
 *
 * @param $server
 *   The server to load domain for, or its id.
 * @return
 *   An array of domain objects indexed by id.
 *
 * @see zmt_domain_load_multiple()
 */
function zmt_domain_load_multiple_by_server($server, $filter_by_user = FALSE, $limit = 0, $offset = 0) {
  global $user;
  $cache = &backdrop_static(__FUNCTION__, array());
  $server_id = is_object($server) ? $server->id : $server;
  $cache_key = md5($server_id . var_export($filter_by_user, TRUE) . $limit . $limit);
  if (!isset($cache[$cache_key])) {
    $query = db_select('zmt_domain', 'zd');
    $query->leftJoin('zmt_tenant', 'zt', 'zt.id = zd.tenant_id');
    $query->leftJoin('users', 'u', 'u.uid = zt.tenant_uid');
    $query->condition('zd.server_id', $server_id);
    if ((int) $limit > 0) {
      $query->range($offset, $limit);
    }
    if ($filter_by_user) {
      if (!(user_access('administer zmt', $user))) {
        if (user_access('administer any zmt_domain', $user)) {
          $query->condition('u.uid', $user->uid);
        }
        elseif (user_access('administer own zmt_domain', $user)) {
          $query->condition('zd.uid', $user->uid);
        }
        else {
          $query->condition('zd.domain_uid', $user->uid);
        }
      }
      $result = $query->fields('zd', array('id'))->execute();
    }
    $result = $query->fields('zd', array('id'))->execute();

    $ids = array();
    foreach ($result as $data) {
      $ids[] = $data->id;
    }
    if (empty($ids)) {
      $ids = module_invoke_all('domain_load_by_user');
    }

    $cache[$cache_key] = zmt_domain_load_multiple($ids);
  }
  return $cache[$cache_key];
}

/**
 * Loads multiple domain by tenant.
 *
 * @param $tenant
 *   The tenant to load domain for, or its id.
 * @return
 *   An array of domain objects indexed by id.
 *
 * @see zmt_domain_load_multiple()
 */
function zmt_domain_load_multiple_by_tenant($tenant, $limit = 0, $offset = 0) {
  $cache = &backdrop_static(__FUNCTION__, array());
  $tenant_id = is_object($tenant) ? (int) $tenant->id : (int) $tenant;
  $cache_key = $tenant_id . '-' . $limit . '-' . $offset;
  if (!isset($cache[$cache_key])) {
    $query = new EntityFieldQuery();
    if ((int) $limit > 0) {
      $efq->range($offset, $limit);
    }
    $result = $query->entityCondition('entity_type', 'zmt_domain')
      ->propertyCondition('tenant_id', $tenant_id)
      ->execute();
    $ids = isset($result['zmt_domain']) ? array_keys($result['zmt_domain']) : array();
    $cache[$cache_key] = zmt_domain_load_multiple($ids);
  }
  return $cache[$cache_key];
}

/**
 * Loads multiple domain by user.
 *
 * @param $domain_user
 *   The user to load domain.
 * @return
 *   An array of domain objects indexed by id.
 *
 * @see zmt_domain_load_multiple()
 */
function zmt_domain_load_multiple_by_user($domain_user = NULL, $limit = 0, $offset = 0) {
  global $user;
  if (NULL === $domain_user) {
    $domain_user = $user;
  }
  $uid = (int) $domain_user->uid;
  $cache = &backdrop_static(__FUNCTION__, array());
  $cache_key = $uid . '-' . $limit . '-' . $offset;
  if (!isset($cache[$cache_key])) {
    $query = db_select('zmt_domain', 'd');
    $query->leftJoin('zmt_tenant', 't', 't.id = d.tenant_id');
    $query->leftJoin('users', 'u', 'u.uid = t.tenant_uid');
    if (!(user_access('administer zmt', $domain_user))) {
      if (user_access('administer any zmt_domain', $domain_user)) {
        $query->condition('u.uid', $uid);
      }
      elseif (user_access('administer own zmt_domain', $domain_user)) {
        $query->condition('d.uid', $uid);
      }
      else {
        $query->condition('d.domain_uid', $uid);
      }
    }
    if ((int) $limit > 0) {
      $query->range($offset, $limit);
    }
    $result = $query->fields('d', array('id'))->execute();

    $ids = array();
    foreach ($result as $data) {
      $ids[] = $data->id;
    }
    if (empty($ids)) {
      $ids = module_invoke_all('domain_load_by_user');
    }
    $cache[$cache_key] = zmt_domain_load_multiple($ids);
  }
  return $cache[$cache_key];
}

/**
 * Loads a domain by name.
 * @param $name
 *   The domain name.
 * @return
 *   A domain object or FALSE.
 */
function zmt_domain_load_by_name($name) {
  $cache = &backdrop_static(__FUNCTION__, array());
  if (!isset($cache[$name])) {
    $query = new EntityFieldQuery();
    $result = $query->entityCondition('entity_type', 'zmt_domain')
      ->propertyCondition('name', $name)
      ->execute();
    $ids = isset($result['zmt_domain']) ? array_keys($result['zmt_domain']) : array();
    $domains = zmt_domain_load_multiple($ids);
    $cache[$name] = $domains ? reset($domains) : FALSE;
  }
  return $cache[$name];
}

/**
 * Loads a domain by zimbra id.
 * @param $zimbra_id
 *   The domain zimbra id.
 * @return
 *   A domain object or FALSE.
 */
function zmt_domain_load_by_zimbra_id($zimbra_id) {
  $cache = &backdrop_static(__FUNCTION__, array());
  if (!isset($cache[$zimbra_id])) {
    $query = new EntityFieldQuery();
    $result = $query->entityCondition('entity_type', 'zmt_domain')
      ->propertyCondition('zimbra_id', $zimbra_id)
      ->execute();
    $ids = isset($result['zmt_domain']) ? array_keys($result['zmt_domain']) : array();
    $domains = zmt_domain_load_multiple($ids);
    $cache[$zimbra_id] = $domains ? reset($domains) : FALSE;
  }
  return $cache[$zimbra_id];
}

/**
 * Get server of domain.
 *
 * @param $id
 *   The domain ID.
 * @return
 *   Server entity object.
 */
function zmt_domain_get_server($id) {
  $domain = zmt_domain_load($id);
  $server_id = $domain ? $domain->server_id : 0;
  return zmt_server_load($server_id);
}

/**
 * Checks domain exists by name.
 *
 * @param $name
 *   The domain name.
 * @param $id
 *   The domain id.
 * @return
 *   TRUE or FALSE.
 */
function zmt_domain_exists($name, $id = 0) {
  $cache = &backdrop_static(__FUNCTION__);
  $cache_key = md5($name . '-' . $id);
  if (!isset($cache[$cache_key])) {
    $query = new EntityFieldQuery();
    $result = $query->entityCondition('entity_type', 'zmt_domain')
      ->propertyCondition('name', $name)
      ->propertyCondition('id', $id, '!=')
      ->count()
      ->execute();
    $cache[$cache_key] = (int) $result > 0;
  }
  return $cache[$cache_key];
}

/**
 * Returns an initialized domain object.
 *
 * @param $name
 *   The machine-readable name of the domain.
 *
 * @return
 *   A domain object with all default fields initialized.
 */
function zmt_domain_new($name = '') {
  global $user;
  $values = array(
    'server_id' => 0,
    'tenant_id' => 0,
    'name' => $name,
    'status' => '',
    'zimbra_id' => '',
    'domain_uid' => 0,
    'uid' => $user->uid,
    'created' => REQUEST_TIME,
    'changed' => REQUEST_TIME,
  );
  return entity_get_controller('zmt_domain')->create($values);
}

/**
 * Saves a domain.
 *
 * @param $domain
 *   The full domain object to save.
 *
 * @return
 *   SAVED_NEW or SAVED_UPDATED depending on the operation performed.
 */
function zmt_domain_save($domain, $by_entity = TRUE) {
  $domain->changed = REQUEST_TIME;
  if ($by_entity === TRUE) {
    return entity_get_controller('zmt_domain')->save($domain);
  }
  else {
    $fields = array(
      'server_id' => $domain->server_id,
      'tenant_id' => $domain->tenant_id,
      'name' => $domain->name,
      'status' => $domain->status,
      'zimbra_id' => $domain->zimbra_id,
      'domain_uid' => $domain->domain_uid,
      'uid' => $domain->uid,
      'created' => $domain->created,
      'changed' => $domain->changed,
    );
    if (!isset($domain->id) || (int) $domain->id == 0) {
      $domain->id = db_insert('zmt_domain')->fields($fields)->execute();
      return SAVED_NEW;
    }
    else {
      db_update('zmt_domain')
        ->fields($fields)
        ->condition('id', $domain->id)
        ->execute();
      entity_get_controller('zmt_domain')->resetCache(array($domain->id));
      return SAVED_UPDATED;
    }
  }
}

/**
 * Deletes a domain by ID.
 *
 * @param $id
 *   The ID of the domain to delete.
 */
function zmt_domain_delete($id) {
  return zmt_domain_delete_multiple(array($id));
}

/**
 * Deletes multiple domain by ID.
 *
 * @param $ids
 *   An array of domain IDs to delete.
 */
function zmt_domain_delete_multiple(array $ids = array()) {
  zmt_domain_cos_delete_multiple_by_domain($ids);
  entity_get_controller('zmt_domain')->delete($ids);
}

/**
 * Deletes multiple domain by ID.
 *
 * @param $ids
 *   An array of domain IDs to delete.
 */
function zmt_domain_delete_multiple_by_server(array $ids = array()) {
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'zmt_domain')
    ->propertyCondition('server_id', $ids)
    ->execute();
  $domain_ids = isset($result['zmt_domain']) ? array_keys($result['zmt_domain']) : array();
  zmt_domain_delete_multiple($domain_ids);
}

/**
 * Loads a domain cos entity by ID.
 */
function zmt_domain_cos_load($id) {
  if (empty($id)) {
    return FALSE;
  }

  $entities = zmt_domain_cos_load_multiple(array($id), array());
  return $entities ? reset($entities) : FALSE;
}

/**
 * Loads multiple domain cos entity by ID or based on a set of matching conditions.
 *
 * @see entity_load()
 *
 * @param $ids
 *   An array of domain cos entity IDs.
 * @param $conditions
 *   An array of conditions on the {zmt_domain_cos} table in the form
 *     'field' => $value.
 * @param $reset
 *   Whether to reset the internal domain cos loading cache.
 *
 * @return
 *   An array of domain cos entity objects indexed by id.
 */
function zmt_domain_cos_load_multiple($ids = array(), array $conditions = array(), $reset = FALSE) {
  if (empty($ids) && empty($conditions)) {
    return array();
  }
  return entity_load('zmt_domain_cos', $ids, $conditions, $reset);
}

/**
 * Loads multiple domain cos entity by cos ids.
 *
 * @see entity_load()
 *
 * @param $cos_ids
 *   An array of cos IDs.
 *
 * @return
 *   An array of entity objects indexed by id.
 */
function zmt_domain_cos_load_multiple_by_cos(array $cos_ids = array(), $domain_id = NULL) {
  if (empty($cos_ids)) {
    $cache = &backdrop_static(__FUNCTION__, array());
    $cache_key = md5(implode(',', $cos_ids) . $domain_id);
    if (!isset($cache[$cache_key])) {
      $efq = new EntityFieldQuery();
      $efq->entityCondition('entity_type', 'zmt_domain_cos')
        ->propertyCondition('cos_id', $cos_ids);
      if (NULL !== $domain_id) {
        $efq->propertyCondition('domain_id', $domain_id);
      }
      $result = $efq->execute();
      $ids = isset($result['zmt_domain_cos']) ? array_keys($result['zmt_domain_cos']) : array();
      $cache[$cache_key] = zmt_domain_cos_load_multiple($ids);
    }
    return $cache[$cache_key];
  }
  return array();
}

/**
 * Loads multiple domain cos entity by domain ids.
 *
 * @see entity_load()
 *
 * @param $domain_ids
 *   An array of domain IDs.
 *
 * @return
 *   An array of entity objects indexed by id.
 */
function zmt_domain_cos_load_multiple_by_domain(array $domain_ids = array(), $cos_id = NULL) {
  if (!empty($domain_ids)) {
    $cache = &backdrop_static(__FUNCTION__, array());
    $cache_key = md5(implode(',', $domain_ids) . $cos_id);
    if (!isset($cache[$cache_key])) {
      $efq = new EntityFieldQuery();
      $efq->entityCondition('entity_type', 'zmt_domain_cos')
        ->propertyCondition('domain_id', $domain_ids);
      if (NULL !== $cos_id) {
        $efq->propertyCondition('cos_id', $cos_id);
      }
      $result = $efq->execute();
      $ids = isset($result['zmt_domain_cos']) ? array_keys($result['zmt_domain_cos']) : array();
      $cache[$cache_key] = zmt_domain_cos_load_multiple($ids);
    }
    return $cache[$cache_key];
  }
  return array();
}

/**
 * Loads a domain cos entity by id of cos and domain.
 */
function zmt_domain_cos_load_single($domain_id, $cos_id) {
  $efq = new EntityFieldQuery();
  $result = $efq->entityCondition('entity_type', 'zmt_domain_cos')
    ->propertyCondition('domain_id', $domain_id)
    ->propertyCondition('cos_id', $cos_id)
    ->execute();
  $ids = isset($result['zmt_domain_cos']) ? array_keys($result['zmt_domain_cos']) : array();
  $entities = zmt_domain_cos_load_multiple($ids);
  return $entities ? reset($entities) : FALSE;
}

/**
 * Returns an initialized domain cos entity object.
 *
 * @param $domain_id
 *   The domain id.
 * @param $cos_id
 *   The cos id.
 *
 * @return
 *   A domain cos entity object with all default fields initialized.
 */
function zmt_domain_cos_new($domain_id = 0, $cos_id = 0) {
  global $user;
  $values = array(
    'domain_id' => (int) $domain_id,
    'cos_id' => (int) $cos_id,
    'max_account' => 0,
    'uid' => $user->uid,
    'created' => REQUEST_TIME,
  );
  return entity_get_controller('zmt_domain_cos')->create($values);
}

/**
 * Saves a domain cos entity.
 *
 * @param $cs
 *   The full domain cos entity object to save.
 *
 * @return
 *   SAVED_NEW or SAVED_UPDATED depending on the operation performed.
 */
function zmt_domain_cos_save($entity, $by_entity = TRUE) {
  if ($by_entity === TRUE) {
    return entity_get_controller('zmt_domain_cos')->save($entity);
  }
  else {
    $fields = array(
      'domain_id' => $entity->domain_id,
      'cos_id' => $entity->cos_id,
      'max_account' => (int) $entity->max_account,
      'uid' => $entity->uid,
      'created' => $entity->created,
    );
    if (!isset($entity->id) || (int) $entity->id == 0) {
      $entity->id = db_insert('zmt_domain_cos')->fields($fields)->execute();
      return SAVED_NEW;
    }
    else {
      db_update('zmt_domain_cos')
        ->fields($fields)
        ->condition('id', $entity->id)
        ->execute();
      entity_get_controller('zmt_domain_cos')->resetCache(array($entity->id));
      return SAVED_UPDATED;
    }
  }
}

/**
 * Deletes a domain cos entity by ID.
 *
 * @param $id
 *   The ID of the domain cos entity to delete.
 */
function zmt_domain_cos_delete($id) {
  return zmt_domain_cos_delete_multiple(array($id));
}

/**
 * Deletes multiple domain cos entity by ID.
 *
 * @param $ids
 *   An array of domain cos entity IDs to delete.
 */
function zmt_domain_cos_delete_multiple(array $ids = array()) {
  entity_get_controller('zmt_domain_cos')->delete($ids);
}

/**
 * Deletes multiple domain cos entity by cos.
 *
 * @param $cos_ids
 *   An array of cos IDs.
 */
function zmt_domain_cos_delete_multiple_by_cos(array $cos_ids = array()) {
  if (!empty($cos_ids)) {
    $efq = new EntityFieldQuery();
    $result = $efq->entityCondition('entity_type', 'zmt_domain_cos')
      ->propertyCondition('cos_id', $cos_ids)
      ->execute();
    $ids = isset($result['zmt_domain_cos']) ? array_keys($result['zmt_domain_cos']) : array();
    zmt_domain_cos_delete_multiple($ids);
  }
}

/**
 * Deletes multiple domain cos entity by domain.
 *
 * @param $domain_ids
 *   An array of domain IDs.
 */
function zmt_domain_cos_delete_multiple_by_domain(array $domain_ids = array()) {
  if (!empty($domain_ids)) {
    $efq = new EntityFieldQuery();
    $result = $efq->entityCondition('entity_type', 'zmt_domain_cos')
      ->propertyCondition('domain_id', $domain_ids)
      ->execute();
    $ids = isset($result['zmt_domain_cos']) ? array_keys($result['zmt_domain_cos']) : array();
    zmt_domain_cos_delete_multiple($ids);
  }
}

/**
 * Define zimbra domain statuses.
 */
function zmt_domain_statuses() {
  return array(
    'active' => t('Active'),
    'closed' => t('Closed'),
    'locked' => t('Locked'),
    'suspended' => t('Suspended'),
    'maintenance' => t('Maintenance'),
  );
}

/**
 * Implements hook_autoload_info().
 */
function zmt_domain_autoload_info() {
  return array(
    'ZmtDomainEntity' => 'zmt_domain.entity.inc',
    'ZmtDomainCosEntity' => 'zmt_domain.entity.inc',
  );
}
