<?php

/**
 * Implements hook_menu().
 */ 
function zmt_account_ui_menu() {
  $items = array();
  $items['zmt/account/%zmt_account'] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('zmt_account', 2),
    'page callback' => 'zmt_account_view',
    'page arguments' => array(2),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'zmt_account', 2),
  );
  $items['zmt/account/add'] = array(
    'title' => t('Add Account'),
    'page callback' => 'zmt_account_add_page',
    'access callback' => 'zmt_account_add_access',
    'type' => MENU_LOCAL_ACTION,
    'file' => 'zmt_account.admin.inc',
  );
  $items['zmt/account/import'] = array(
    'title' => t('Import Account'),
    'page callback' => 'zmt_account_import_page',
    'access callback' => 'zmt_account_add_access',
    'type' => MENU_LOCAL_ACTION,
    'file' => 'zmt_account.admin.inc',
  );
  $items['zmt/account/importing/progress/%'] = array(
    'title' => t('Importing Progress Bar'),
    'page callback' => 'zmt_account_importing_progress',
    'page arguments' => array(4),
    'access callback' => 'zmt_account_add_access',
    'type' => MENU_CALLBACK,
    'file' => 'zmt_account.admin.inc',
  );
  $items['zmt/account/%zmt_account/edit'] = array(
    'title' => t('Edit Account'),
    'page callback' => 'zmt_account_edit_page',
    'page arguments' => array(2),
    'access callback' => 'zmt_account_edit_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK,
    'file' => 'zmt_account.admin.inc',
  );
  $items['zmt/account/%zmt_account/delete'] = array(
    'title' => t('Delete Account'),
    'page callback' => 'zmt_account_delete_page',
    'page arguments' => array(2),
    'access callback' => 'zmt_account_delete_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK,
    'file' => 'zmt_account.admin.inc',
  );
  $items['zmt/account'] = array(
    'title' => t('Accounts'),
    'page callback' => 'zmt_account_list_all',
    'access callback' => 'zmt_account_list_access',
    'file' => 'zmt_account.admin.inc',
  );
  $items['zmt/account/quota'] = array(
    'title' => 'Mailbox Quota',
    'page callback' => 'zmt_account_quota_usage',
    'access callback' => 'zmt_account_quota_usage_access',
    'file' => 'zmt_account.admin.inc',
  );
  return $items;
}

/**
 * Account view callback.
 */
function zmt_account_view($account) {
  drupal_set_title(entity_label('zmt_account', $account));
  return entity_view('zmt_account', array(entity_id('zmt_account', $account) => $account), 'full');
}

/**
 * Access callback: determines if the user can create account.
 */
function zmt_account_list_access($account = NULL) {
  return zmt_account_access('list', NULL, $account);
}

/**
 * Access callback: determines if the user can create account.
 */
function zmt_account_add_access($account = NULL) {
  return zmt_account_access('create', NULL, $account);
}

/**
 * Access callback: determines if the user can edit account.
 */
function zmt_account_edit_access($acc, $account = NULL) {
  global $user;
  if (NULL === $account) {
    $account = $user;
  }
  if (user_access('administer zmt', $account)) {
    return TRUE;
  }
  if (user_access('administer any zmt_account', $account)) {
    $domains = zmt_domain_load_multiple_by_user($user);
    $domain_ids = array_keys($domains);
    $access = in_array($acc->domain_id, $domain_ids);
    foreach (module_implements('zmt_account_edit_access') as $module) {
      $access = $access && (bool) module_invoke($module, 'zmt_account_edit_access', $acc);
    }
    return $access;
  }
  if (user_access('administer own zmt_account', $account)) {
    return $acc->uid == $account->uid;
  }
}

/**
 * Access callback: determines if the user can delete account.
 */
function zmt_account_delete_access($acc, $account = NULL) {
  return zmt_account_edit_access($acc, $account);
}

/**
 * Quota Usage Callback
 */
function zmt_account_quota_usage_access($account = NULL) {
  global $user;
  if (NULL === $account) {
    $account = $user;
  }
  if (user_access('administer zmt', $account)) {
    return TRUE;
  }
}
