<?php

/**
 * Implements hook_menu().
 */ 
function zmt_group_ui_menu() {
  $items = array();
  $items['zmt/group/%zmt_group'] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('zmt_group', 2),
    'page callback' => 'zmt_group_view',
    'page arguments' => array(2),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'zmt_group', 2),
  );
  $items['zmt/group/add'] = array(
    'title' => 'Add Group',
    'page callback' => 'zmt_group_add_page',
    'access callback' => 'zmt_group_add_access',
    'type' => MENU_LOCAL_ACTION,
    'file' => 'zmt_group.admin.inc',
  );
  $items['zmt/group/%zmt_group/edit'] = array(
    'title' => 'Edit Group',
    'page callback' => 'zmt_group_edit_page',
    'page arguments' => array(2),
    'access callback' => 'zmt_group_edit_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK,
    'file' => 'zmt_group.admin.inc',
  );
  $items['zmt/group/%zmt_group/delete'] = array(
    'title' => 'Delete Group',
    'page callback' => 'zmt_group_delete_page',
    'page arguments' => array(2),
    'access callback' => 'zmt_group_delete_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK,
    'file' => 'zmt_group.admin.inc',
  );
  $items['zmt/group'] = array(
    'title' => 'Groups',
    'page callback' => 'zmt_group_list_all',
    'access callback' => 'zmt_group_list_access',
    'file' => 'zmt_group.admin.inc',
    '#weight' => 3,
  );
  return $items;
}

/**
 * Group view callback.
 */
function zmt_group_view($group) {
  drupal_set_title(entity_label('zmt_group', $group));
  return entity_view('zmt_group', array(entity_id('zmt_group', $group) => $group), 'full');
}

/**
 * Access callback: determines if the user can create group.
 */
function zmt_group_list_access($account = NULL) {
  return zmt_group_access('list', NULL, $account);
}

/**
 * Access callback: determines if the user can create group.
 */
function zmt_group_add_access($account = NULL) {
  return zmt_group_access('create', NULL, $account);
}

/**
 * Access callback: determines if the user can edit group.
 */
function zmt_group_edit_access($group, $account = NULL) {
  global $user;
  if (NULL === $account) {
    $account = $user;
  }
  if (user_access('administer zmt', $account)) {
    return TRUE;
  }
  else {
    $domains = zmt_domain_load_multiple_by_user($account);
    $domain_ids = array_keys($domains);
    if (!empty($domain_ids)) {
      return in_array($group->domain_id, $domain_ids);
    }
    else {
      return (int) $group->group_uid == (int) $account->uid;
    }
  }
  return FALSE;
}

/**
 * Access callback: determines if the user can delete group.
 */
function zmt_group_delete_access($group, $account = NULL) {
  return zmt_group_access('delete', $group, $account);
}
